import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import SideMenu from '@/components/ui/SideMenu'
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from '@/components/ui/toggle-button'
import Image from 'next/image'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gallery gleam | Your personal gallery images',
  description: 'Generated by next js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <Image src='/logo-icon.png' width="40" height="40" alt="icon of this album app"/>
            <h1 className='font-bold text-xl pl-2'>
              GALLERY GLEAM
            </h1>
            <div className="ml-auto flex items-center space-x-4">
              <ModeToggle/>
             <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                
              </div>
          </div>
        </div>
        <div className='flex'>
        <SideMenu/>
        <div className='w-full px-4 py-2'>
          {children}
        </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
